# Generated by Django 5.2.17 on 2026-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Категория')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Файл')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML')], max_length=8, verbose_name='Формат')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('partial', 'Частично'), ('error', 'Ошибка')], max_length=8, verbose_name='Статус')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='Отчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортировано')),
            ],
            options={
                'verbose_name': 'Импорт',
                'verbose_name_plural': 'Импорты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('aries', 'Овен'), ('taurus', 'Телец'), ('gemini', 'Близнецы'), ('cancer', 'Рак'), ('leo', 'Лев'), ('virgo', 'Дева'), ('libra', 'Весы'), (Водолей'scorpio', 'Скорпион'), ('sagittarius', 'Стрелец'), ('capricorn', 'Козерог'), ('aquarius', ''), ('pisces', 'Рыбы')], db_index=True, max_length=16, verbose_name='Знак зодиака')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
                'ordering': ('date', 'sign'),
                'unique_together': {('sign', 'date')},
            },
        ),
    ]
