# Generated by Django 5.2.17 on 2026-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle_facts', models.BooleanField(default=False, help_text='Если включено, API отдаёт факты в случайном порядке (при ограничении limit — случайную выборку на каждый запрос).', verbose_name='Перемешивать факты')),
                ('shuffle_horoscopes', models.BooleanField(default=False, help_text='Если включено, запрос без параметра sign вернёт все знаки в случайном порядке (порядок меняется при каждом обращении).', verbose_name='Перемешивать гороскопы')),
            ],
            options={
                'verbose_name': 'Настройки показа',
                'verbose_name_plural': 'Настройки показа',
            },
        ),
    ]
