# Generated by Django 5.2.17 on 2026-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Не проверено после импорта (не показывается на экранах)', verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=8, verbose_name='Формат'),
        ),
    ]
