# Generated by Django 5.2.17 on 2026-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_horoscope_is_draft_alter_importlog_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='scheduled_fact_category',
            field=models.CharField(blank=True, help_text='В указанный период API отдаёт только активные факты этой категории.', max_length=64, verbose_name='Категория фактов по расписанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scheduled_facts_end',
            field=models.DateField(blank=True, help_text='Начальная и конечная даты входят в период.', null=True, verbose_name='Окончание периода'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scheduled_facts_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало периода'),
        ),
    ]
